trigger:
  - master

pool: 'Khairoooon'

variables:
  buildConfiguration: 'Release'

steps:  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Shared/AH.Shared.Domain/AH.Shared.Domain.csproj'
  
  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration)'
      packagesToPack: 'Shared/AH.Shared.Domain/AH.Shared.Domain.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Shared/AH.Shared.Application/AH.Shared.Application.csproj'

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration)'
      packagesToPack: 'Shared/AH.Shared.Application/AH.Shared.Application.csproj'
      nobuild: true
      versioningScheme: 'off'
      
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Shared/AH.Shared.Infrastructure/AH.Shared.Infrastructure.csproj'

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration)'
      packagesToPack: 'Shared/AH.Shared.Infrastructure/AH.Shared.Infrastructure.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Shared/AH.Shared.Persistence/AH.Shared.Persistence.csproj'

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration)'
      packagesToPack: 'Shared/AH.Shared.Persistence/AH.Shared.Persistence.csproj'
      nobuild: true
      versioningScheme: 'off'
      
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'AH.Microservices.Metadata/Src/Shared/AH.Metadata.Shared.V1/AH.Metadata.Shared.V1.csproj'

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration)'
      packagesToPack: 'AH.Microservices.Metadata/Src/Shared/AH.Metadata.Shared.V1/AH.Metadata.Shared.V1.csproj'
      nobuild: true
      versioningScheme: 'off'
  
  - task: NuGetCommand@2
    displayName: 'nuget push'
    inputs:
      command: 'push'
      feedsToUse: 'select'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'eelkhair'
      versioningScheme: 'off'
      allowPackageConflicts: true