version: '3.4'

services:
  ah-company-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
      - "5003:8080"
  
  ah-team-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5012:8080"
      - "5013:8080"
 
  ah-metadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
 
  ah-user-api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
       - "5004:8080"
       - "5005:8080"  
  
  ah-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:  
      - "5010:80"
      - "5011:80"
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
  
  ah-status:
    environment:
      - HealthChecksUI__HealthChecks__0__Name=AH Metadata API
      - HealthChecksUI__HealthChecks__0__Uri=http://ah-metadata-api:8080/healthzEndpoint     
      - HealthChecksUI__HealthChecks__1__Name=AH Company API
      - HealthChecksUI__HealthChecks__1__Uri=http://ah-company-api:8080/healthzEndpoint 
      - HealthChecksUI__HealthChecks__2__Name=AH User API
      - HealthChecksUI__HealthChecks__2__Uri=http://ah-user-api:8080/healthzEndpoint
      - HealthChecksUI__HealthChecks__3__Name=AH Team API
      - HealthChecksUI__HealthChecks__3__Uri=http://ah-team-api:8080/healthzEndpoint
    
    ports:
      - "5107:8080"