version: '3.4'

services:
  ah-company-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
      - "5003:8080"
  ah-metadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
 
  ah-user-api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
       - "5004:8080"
       - "5005:8080"  
  
  ah-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:  
      - "5010:8080"

   