version: '3.4'

services:
  ah-company-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
      - "5003:8080"
  ##  volumes:
    #  - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro'
  ah-metadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
   # volumes:
    #  - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
 
  ah-user-api:
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     ports:
       - "5004:8080"
       - "5005:8080"
 #    volumes:
 #      - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
 
 
  
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
