version: '3.4'

services:
  ah-company-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
      - "5003:8080"
  ##  volumes:
    #  - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro'
  ah-metadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
   # volumes:
    #  - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
 
  ah-user-api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
       - "5004:8080"
       - "5005:8080"  
       
       
  
  ah-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:8081;http://+:8080
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass321$
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/AH.Web.pfx
    ports:  
      - "5010:8080"
#    volumes:
#      - ~/.aspnet/https:/https:ro
   