version: '3.4'

services:
  ah-company-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
      - "5003:8080"
  ah-metadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
 
  ah-user-api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
       - "5004:8080"
       - "5005:8080"  
  
  ah-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:  
      - "5010:80"
      - "5011:80"
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
  
  web-status:
    environment:
      - HealthChecksUI__HealthChecks__0__Name=AH Metadata API
      - HealthChecksUI__HealthChecks__0__Uri=http://ah-metadata-api:8080/healthzEndpoint
    
    ports:
      - "5107:8080"