version: '3.4'

services:
  ah-company-api:
    image: ${DOCKER_REGISTRY-}ahcompanyapi
    build:
      context: .
      dockerfile: AH.Microservices.Company/Src/Presentation/AH.Company.Api/Dockerfile 
  ah-user-api:
    image: ${DOCKER_REGISTRY-}ahuserapi
    build:
      context: .
      dockerfile: AH.Microservices.User/Src/Presentation/AH.User.Api/Dockerfile  
  ah-metadata-api:
    image: ${DOCKER_REGISTRY-}ahmetadataapi
    build:
      context: .
      dockerfile: AH.Microservices.Metadata/Src/Presentation/AH.Metadata.Api/Dockerfile
    env_file: ".env"    
  ah-company-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-company-api",
      "--app-port", "80",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--components-path", "./Components"      
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - ah-company-api
      - placement
    network_mode: "service:ah-company-api"  
            
  ah-metadata-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-metadata-api",
      "--app-port", "80",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "./Components"
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - ah-metadata-api
      - placement
    network_mode: "service:ah-metadata-api"
  
  ah-user-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-user-api",
      "--app-port", "80",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "./Components"
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - ah-user-api
      - placement
    network_mode: "service:ah-user-api"
    
  placement:
    image: "daprio/dapr"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
  
  