version: '3.4'

services:
  ah-company-api:
      image: ${DOCKER_REGISTRY-}ah-company-api
      build:
        context: .
        dockerfile: AH.Microservices.Company/Src/Presentation/AH.Company.Api/Dockerfile
      
  ah-team-api:
    image: ${DOCKER_REGISTRY-}ah-team-api
    build:
      context: .
      dockerfile: AH.Microservices.Team/Src/Presentation/AH.Team.Api/Dockerfile
        
  ah-web:
    image: ${DOCKER_REGISTRY-}ah-web
    build:
      context: .
      dockerfile: FrontEnd/AH.Web/Server/Dockerfile
  
  ah-user-api:
    image: ${DOCKER_REGISTRY-}ah-user-api
    build:
      context: .
      dockerfile: AH.Microservices.User/Src/Presentation/AH.User.Api/Dockerfile  
      
  ah-metadata-api:
    image: ${DOCKER_REGISTRY-}ah-metadata-api
    build:
      context: .
      dockerfile: AH.Microservices.Metadata/Src/Presentation/AH.Metadata.Api/Dockerfile
  
  ah-company-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-company-api",
      "--app-port", "8080",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "./Components",
      "--resources-path", "./Dapr/Components/Secrets",
      "--resources-path", "./Dapr/Components/Timers",
      "--log-level" ,"debug",
      "-config", "./Config/config.yaml"
    ]   
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./AH.Microservices.Company/Src/Presentation/AH.Company.Api/Dapr/Components:/Dapr/Components"
      - "./Config/:/Config"
    depends_on:
      - ah-company-api
      - placement
    network_mode: "service:ah-company-api"  
        
  ah-team-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-team-api",
      "--app-port", "8080",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "./Components",
      "--resources-path", "./Dapr/Components/Secrets",
      "--resources-path", "./Dapr/Components/Timers",
      "--log-level" ,"debug",
      "-config", "./Config/config.yaml"
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./AH.Microservices.Team/Src/Presentation/AH.Team.Api/Dapr/Components:/Dapr/Components"
      - "./Config/:/Config"
    depends_on:
      - ah-team-api
      - placement
    network_mode: "service:ah-team-api"
  
  ah-metadata-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-metadata-api",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "./Components",
      "--resources-path", "./Dapr/Components/Secrets",
      "--resources-path", "./Dapr/Components/Timers",
      "-config", "./Config/config.yaml",
      "--log-level" ,"debug",
      "--app-port", "8080"
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./AH.Microservices.Metadata/Src/Presentation/AH.Metadata.Api/Dapr/Components:/Dapr/Components"
      - "./Config/:/Config"
    depends_on:
      - ah-metadata-api
      - placement
    network_mode: "service:ah-metadata-api"
  
  ah-user-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-user-api",
      "--app-port", "8080",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "./Components",
      "--resources-path", "./Dapr/Components/Secrets",
      "--resources-path", "./Dapr/Components/Timers",
      "--log-level" ,"debug",
      "-config", "./Config/config.yaml"
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./AH.Microservices.User/Src/Presentation/AH.User.Api/Dapr/Components:/Dapr/Components"
      - "./Config/:/Config"
    depends_on:
      - ah-user-api
      - placement
    network_mode: "service:ah-user-api"

  ah-web-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-web",
      "--app-port", "8080",
      "--components-path", "./Components",
      "-config", "./Config/config.yaml",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./Config/:/Config"
    depends_on:
      - ah-web
      - placement
    network_mode: "service:ah-web"
    
  seq:
    image: datalust/seq:latest

  placement:
    image: "daprio/dapr"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
      
  ah-status:
    image: ${DOCKER_REGISTRY-}ahwebstatus
    build:
      context: .
      dockerfile: HealthChecks/AH.Microservices.WebStatus/Dockerfile