version: '3.4'

services:
  ah-company-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
      - "5003:8080"
  ##  volumes:
    #  - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro'
  ah-metadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
   # volumes:
    #  - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
 
  ah-user-api:
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     ports:
       - "5004:8080"
       - "5005:8080"
 #    volumes:
 #      - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  agilityhealth-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5010:8080"
     
  #  volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
   #   - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
