version: '3.4'

services:
  ah-company-api:
      image: ${DOCKER_REGISTRY-}ahcompanyapi
      build:
        context: .
        dockerfile: AH.Microservices.Company/Src/Presentation/AH.Company.Api/Dockerfile
  ah-web:
     image: ${DOCKER_REGISTRY-}ahweb
     build:
       context: .
       dockerfile: FrontEnd/AH.Web/Dockerfile
  
  ah-user-api:
    image: ${DOCKER_REGISTRY-}ahuserapi
    build:
      context: .
      dockerfile: AH.Microservices.User/Src/Presentation/AH.User.Api/Dockerfile  
  ah-metadata-api:
    image: ${DOCKER_REGISTRY-}ahmetadataapi
    build:
      context: .
      dockerfile: AH.Microservices.Metadata/Src/Presentation/AH.Metadata.Api/Dockerfile
  
  ah-company-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-company-api",
      "--app-port", "8080",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--components-path", "./Components",
      "-config", "./Config/config.yaml"
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./Config/:/Config"
    depends_on:
      - ah-company-api
      - placement
    network_mode: "service:ah-company-api"
    
      
  ah-metadata-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-metadata-api",
      "--app-port", "8080",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--components-path", "./Components",
      "-config", "./Config/config.yaml"
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./Config/:/Config"
    depends_on:
      - ah-metadata-api
      - placement
    network_mode: "service:ah-metadata-api"
  
  ah-user-api-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-user-api",
      "--app-port", "8080",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--components-path", "./Components",
      "-config", "./Config/config.yaml"
    ]
    volumes:
      - "./Components/:/Components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./Config/:/Config"
    depends_on:
      - ah-user-api
      - placement
    network_mode: "service:ah-user-api"

  ah-web-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "ah-web",
      "--app-port", "8080",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
    ]
    depends_on:
      - ah-web
      - placement
    network_mode: "service:ah-web"
  
  
  placement:
    image: "daprio/dapr"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"




 

