version: '3.4'

services:
  ah-company-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5022:80"
      - "5023:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro'
  ah-metadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5021:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  ah-company-orchestration-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5024:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro