version: '3.4'

services:
  ah-company-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
      - "5003:80"
  ##  volumes:
    #  - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro'
  ah-metadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
   # volumes:
    #  - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
 
  ah-user-api:
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     ports:
       - "5004:80"
       - "5005:80"
 #    volumes:
 #      - ${Home}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro