version: '3.4'

services:
  agilityhealth-metadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5011:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro