apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis.pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: 192.168.1.160:6379
    - name: redisPassword
      value: ""
    - name: consumerID
      value: "myGroup"
    - name: enableTLS
      value: "false"