apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore.redis
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: 192.168.1.160:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
